// This file is auto-generated by @hey-api/openapi-ts

export const CreateInvestmentDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: ['id']
} as const;

export const CreateTransactionDtoSchema = {
    type: 'object',
    properties: {}
} as const;

export const UpdateTransactionDtoSchema = {
    type: 'object',
    properties: {}
} as const;

export const CreateStakingDtoSchema = {
    type: 'object',
    properties: {
        investmentId: {
            type: 'string'
        },
        amount: {
            type: 'number'
        },
        storageLocationId: {
            type: 'string'
        },
        websiteLink: {
            type: 'string'
        },
        coolDownPeriod: {
            type: 'number'
        },
        startDate: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: ['investmentId', 'amount', 'storageLocationId', 'websiteLink', 'coolDownPeriod', 'startDate']
} as const;

export const UpdateStakingDtoSchema = {
    type: 'object',
    properties: {
        amount: {
            type: 'number'
        },
        storageLocationId: {
            type: 'string'
        },
        websiteLink: {
            type: 'string'
        },
        coolDownPeriod: {
            type: 'number'
        },
        startDate: {
            format: 'date-time',
            type: 'string'
        }
    }
} as const;

export const CreateStorageLocationDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        image: {
            type: 'string'
        },
        storageLocationType: {
            type: 'string',
            enum: ['hardwareWallet', 'softwareWallet', 'exchange']
        }
    },
    required: ['name', 'image', 'storageLocationType']
} as const;

export const UpdateStorageLocationDtoSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        image: {
            type: 'string'
        },
        storageLocationType: {
            type: 'string',
            enum: ['hardwareWallet', 'softwareWallet', 'exchange']
        }
    }
} as const;

export const CreateStorageDtoSchema = {
    type: 'object',
    properties: {
        investmentId: {
            type: 'string'
        },
        amount: {
            type: 'number'
        },
        storageLocationId: {
            type: 'string'
        },
        date: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: ['investmentId', 'amount', 'storageLocationId', 'date']
} as const;

export const UpdateStorageDtoSchema = {
    type: 'object',
    properties: {
        amount: {
            type: 'number'
        },
        storageLocationId: {
            type: 'string'
        },
        date: {
            format: 'date-time',
            type: 'string'
        }
    },
    required: ['amount', 'storageLocationId', 'date']
} as const;