// This file is auto-generated by @hey-api/openapi-ts

import type { InvestmentsControllerGetAllInvestmentsResponse, InvestmentsControllerCreateInvestmentResponse, InvestmentsControllerGetInvestmentByIdResponse, InvestmentsControllerGetInvestmentBySymbolResponse, CoingeckoControllerGetAllMarketChartDataResponse, CoingeckoControllerGetMarketChartDataResponse, TransactionsControllerGetAllTransactionsResponse, TransactionsControllerCreateTransactionResponse, TransactionsControllerGetAllTransactionsForInvestmentIdResponse, TransactionsControllerGetTransactionByIdResponse, TransactionsControllerUpdateTransactionResponse, StakingsControllerGetAllStakingsResponse, StakingsControllerCreateStakingResponse, StakingsControllerGetStakingByIdResponse, StakingsControllerUpdateStakingResponse, StorageControllerFindAllResponse, StorageControllerCreateResponse, StorageControllerFindOneResponse, StorageControllerUpdateResponse, PortfolioControllerGetPortfolioHistoryResponse } from './types.gen';

const transactionEntitySchemaResponseTransformer = (data: any) => {
    data.date = new Date(data.date);
    return data;
};

const storageEntitySchemaResponseTransformer = (data: any) => {
    data.date = new Date(data.date);
    return data;
};

const stakingEntitySchemaResponseTransformer = (data: any) => {
    data.startDate = new Date(data.startDate);
    return data;
};

const investmentEntitySchemaResponseTransformer = (data: any) => {
    data.transactions = data.transactions.map(item => {
        return transactionEntitySchemaResponseTransformer(item);
    });
    data.storages = data.storages.map(item => {
        return storageEntitySchemaResponseTransformer(item);
    });
    data.stakings = data.stakings.map(item => {
        return stakingEntitySchemaResponseTransformer(item);
    });
    return data;
};

export const investmentsControllerGetAllInvestmentsResponseTransformer = async (data: any): Promise<InvestmentsControllerGetAllInvestmentsResponse> => {
    data = data.map(item => {
        return investmentEntitySchemaResponseTransformer(item);
    });
    return data;
};

export const investmentsControllerCreateInvestmentResponseTransformer = async (data: any): Promise<InvestmentsControllerCreateInvestmentResponse> => {
    data = investmentEntitySchemaResponseTransformer(data);
    return data;
};

export const investmentsControllerGetInvestmentByIdResponseTransformer = async (data: any): Promise<InvestmentsControllerGetInvestmentByIdResponse> => {
    data = investmentEntitySchemaResponseTransformer(data);
    return data;
};

export const investmentsControllerGetInvestmentBySymbolResponseTransformer = async (data: any): Promise<InvestmentsControllerGetInvestmentBySymbolResponse> => {
    data = investmentEntitySchemaResponseTransformer(data);
    return data;
};

const chartDataEntitySchemaResponseTransformer = (data: any) => {
    data.timestamp = new Date(data.timestamp);
    return data;
};

export const coingeckoControllerGetAllMarketChartDataResponseTransformer = async (data: any): Promise<CoingeckoControllerGetAllMarketChartDataResponse> => {
    data = data.map(item => {
        return chartDataEntitySchemaResponseTransformer(item);
    });
    return data;
};

export const coingeckoControllerGetMarketChartDataResponseTransformer = async (data: any): Promise<CoingeckoControllerGetMarketChartDataResponse> => {
    data = data.map(item => {
        return chartDataEntitySchemaResponseTransformer(item);
    });
    return data;
};

export const transactionsControllerGetAllTransactionsResponseTransformer = async (data: any): Promise<TransactionsControllerGetAllTransactionsResponse> => {
    data = data.map(item => {
        return transactionEntitySchemaResponseTransformer(item);
    });
    return data;
};

export const transactionsControllerCreateTransactionResponseTransformer = async (data: any): Promise<TransactionsControllerCreateTransactionResponse> => {
    data = transactionEntitySchemaResponseTransformer(data);
    return data;
};

export const transactionsControllerGetAllTransactionsForInvestmentIdResponseTransformer = async (data: any): Promise<TransactionsControllerGetAllTransactionsForInvestmentIdResponse> => {
    data = data.map(item => {
        return transactionEntitySchemaResponseTransformer(item);
    });
    return data;
};

export const transactionsControllerGetTransactionByIdResponseTransformer = async (data: any): Promise<TransactionsControllerGetTransactionByIdResponse> => {
    data = transactionEntitySchemaResponseTransformer(data);
    return data;
};

export const transactionsControllerUpdateTransactionResponseTransformer = async (data: any): Promise<TransactionsControllerUpdateTransactionResponse> => {
    data = transactionEntitySchemaResponseTransformer(data);
    return data;
};

export const stakingsControllerGetAllStakingsResponseTransformer = async (data: any): Promise<StakingsControllerGetAllStakingsResponse> => {
    data = data.map(item => {
        return stakingEntitySchemaResponseTransformer(item);
    });
    return data;
};

export const stakingsControllerCreateStakingResponseTransformer = async (data: any): Promise<StakingsControllerCreateStakingResponse> => {
    data = stakingEntitySchemaResponseTransformer(data);
    return data;
};

export const stakingsControllerGetStakingByIdResponseTransformer = async (data: any): Promise<StakingsControllerGetStakingByIdResponse> => {
    data = stakingEntitySchemaResponseTransformer(data);
    return data;
};

export const stakingsControllerUpdateStakingResponseTransformer = async (data: any): Promise<StakingsControllerUpdateStakingResponse> => {
    data = stakingEntitySchemaResponseTransformer(data);
    return data;
};

export const storageControllerFindAllResponseTransformer = async (data: any): Promise<StorageControllerFindAllResponse> => {
    data = data.map(item => {
        return storageEntitySchemaResponseTransformer(item);
    });
    return data;
};

export const storageControllerCreateResponseTransformer = async (data: any): Promise<StorageControllerCreateResponse> => {
    data = storageEntitySchemaResponseTransformer(data);
    return data;
};

export const storageControllerFindOneResponseTransformer = async (data: any): Promise<StorageControllerFindOneResponse> => {
    data = storageEntitySchemaResponseTransformer(data);
    return data;
};

export const storageControllerUpdateResponseTransformer = async (data: any): Promise<StorageControllerUpdateResponse> => {
    data = storageEntitySchemaResponseTransformer(data);
    return data;
};

const portfolioHistoryEntitySchemaResponseTransformer = (data: any) => {
    data.timestamp = new Date(data.timestamp);
    return data;
};

export const portfolioControllerGetPortfolioHistoryResponseTransformer = async (data: any): Promise<PortfolioControllerGetPortfolioHistoryResponse> => {
    data = data.map(item => {
        return portfolioHistoryEntitySchemaResponseTransformer(item);
    });
    return data;
};