// This file is auto-generated by @hey-api/openapi-ts

export type CreateInvestmentDto = {
    coinId: string;
};

export type type = 'buy' | 'sell';

export const type = {
    BUY: 'buy',
    SELL: 'sell'
} as const;

export type CreateTransactionDto = {
    investmentId: string;
    quantity: number;
    price: number;
    date: Date;
    type: 'buy' | 'sell';
};

export type UpdateTransactionDto = {
    quantity?: number;
    price?: number;
    date?: Date;
    type?: 'buy' | 'sell';
};

export type CreateStakingDto = {
    investmentId: string;
    amount: number;
    storageLocationId: string;
    websiteLink: string;
    coolDownPeriod: number;
    startDate: Date;
};

export type UpdateStakingDto = {
    amount?: number;
    storageLocationId?: string;
    websiteLink?: string;
    coolDownPeriod?: number;
    startDate?: Date;
};

export type storageLocationType = 'hardwareWallet' | 'softwareWallet' | 'exchange';

export const storageLocationType = {
    HARDWAREWALLET: 'hardwareWallet',
    SOFTWAREWALLET: 'softwareWallet',
    EXCHANGE: 'exchange'
} as const;

export type CreateStorageLocationDto = {
    name: string;
    image: string;
    storageLocationType: 'hardwareWallet' | 'softwareWallet' | 'exchange';
};

export type UpdateStorageLocationDto = {
    name?: string;
    image?: string;
    storageLocationType?: 'hardwareWallet' | 'softwareWallet' | 'exchange';
};

export type CreateStorageDto = {
    investmentId: string;
    amount: number;
    storageLocationId: string;
    date: Date;
};

export type UpdateStorageDto = {
    amount: number;
    storageLocationId: string;
    date: Date;
};

export type InvestmentsControllerCreateInvestmentData = {
    body: CreateInvestmentDto;
};

export type InvestmentsControllerDeleteInvestmentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
};

export type InvestmentsControllerGetInvestmentByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
};

export type InvestmentsControllerGetInvestmentBySymbolData = {
    body?: never;
    path: {
        symbol: string;
    };
    query?: never;
};

export type CoingeckoControllerGetAllMarketChartDataData = {
    body?: never;
    path?: never;
    query: {
        days: string;
    };
};

export type CoingeckoControllerGetMarketChartDataData = {
    body?: never;
    path: {
        coinId: string;
    };
    query: {
        days: number;
    };
};

export type TransactionsControllerCreateTransactionData = {
    body: CreateTransactionDto;
};

export type TransactionsControllerGetAllTransactionsForInvestmentIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
};

export type TransactionsControllerDeleteTransactionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
};

export type TransactionsControllerGetTransactionByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
};

export type TransactionsControllerUpdateTransactionData = {
    body: UpdateTransactionDto;
    path: {
        id: string;
    };
    query?: never;
};

export type StakingsControllerCreateStakingData = {
    body: CreateStakingDto;
};

export type StakingsControllerDeleteStakingData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
};

export type StakingsControllerGetStakingByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
};

export type StakingsControllerUpdateStakingData = {
    body: UpdateStakingDto;
    path: {
        id: string;
    };
    query?: never;
};

export type StorageLocationsControllerCreateData = {
    body: CreateStorageLocationDto;
};

export type StorageLocationsControllerDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
};

export type StorageLocationsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
};

export type StorageLocationsControllerUpdateData = {
    body: UpdateStorageLocationDto;
    path: {
        id: string;
    };
    query?: never;
};

export type StorageControllerCreateData = {
    body: CreateStorageDto;
};

export type StorageControllerDeleteData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
};

export type StorageControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
};

export type StorageControllerUpdateData = {
    body: UpdateStorageDto;
    path: {
        id: string;
    };
    query?: never;
};

export type StorageControllerFindByInvestmentData = {
    body?: never;
    path: {
        investmentId: string;
    };
    query?: never;
};